setw -g mouse on
setw -g mode-keys vi

# Window title
set -g set-titles on
set -g set-titles-string "#S"

# Colours
set -g default-terminal "tmux-256color"
set -g @color_bg "colour234"
set -g @color_text "colour0"
# For macOS
set -g @color_1 "colour27"
set -g @color_2 "colour33"
set -g @color_3 "colour39"
set -g @color_4 "colour45"
# For Linux
#set -g @color_1 "colour22"
#set -g @color_2 "colour28"
#set -g @color_3 "colour34"
#set -g @color_4 "colour40"

set -g status-style "fg=#{@color_text},bg=#{@color_1}"
set -g pane-border-style "fg=#{@color_1}"
set -g pane-active-border-style "fg=#{@color_4}"

# Status
set -g status-interval 1
# Togge status bar
bind t run-shell "tmux setw -g status $(tmux show -g status | grep -q off && echo on || echo off)"
# LEFT: > path > git branch > git status >
set -g status-left-length 100
set -g status-left '\
#[bg=#{@color_4},fg=#{@color_bg}]\
#[bg=#{@color_4},fg=#{@color_text}] #{pane_current_path} \
#[bg=#{@color_3},fg=#{@color_4}]\
#[bg=#{@color_3},fg=#{@color_text}]#(branch=$(git -C "#{pane_current_path}" rev-parse --abbrev-ref HEAD 2>/dev/null) && [ -n "$branch" ] && echo " $branch " || echo " ")\
#[bg=#{@color_2},fg=#{@color_3}]\
#[bg=#{@color_2},fg=#{@color_text}]#(status=$(git -C "#{pane_current_path}" status --porcelain 2>/dev/null) && a=$(echo "$status" | grep "^A" | wc -l | xargs) && m=$(echo "$status" | grep "^ M" | wc -l | xargs) && r=$(echo "$status" | grep "^ D" | wc -l | xargs) && u=$(echo "$status" | grep "^??" | wc -l | xargs) && output="" && [ "$a" -gt 0 ] && output="$output +$a" ; [ "$m" -gt 0 ] && output="$output ~$m" ; [ "$r" -gt 0 ] && output="$output -$r" ; [ "$u" -gt 0 ] && output="$output ×$u" ; echo "$output ")\
#[bg=#{@color_1},fg=#{@color_2}]\
'
# RIGHT: > session > user@host > weekday date time >
set -g status-right-length 100
set -g status-right "\
#[bg=#{@color_2},fg=#{@color_1}]\
#[bg=#{@color_2},fg=#{@color_text}] #S \
#[bg=#{@color_3},fg=#{@color_2}]\
#[bg=#{@color_3},fg=#{@color_text}] #(whoami)@#H \
#[bg=#{@color_4},fg=#{@color_3}]\
#[bg=#{@color_4},fg=#{@color_text}] %a %Y-%m-%d %H:%M:%S \
#[bg=#{@color_bg},fg=#{@color_4}]\
"
# CENTER
set -g status-justify left
set -g window-status-format ""
set -g window-status-current-format ""
